export const orderConstants = {

    ORDER_CREATE_REQUEST : 'ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS : 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL : 'ORDER_CREATE_FAIL',


    ORDER_CREATE_RESET : 'ORDER_CREATE_RESET',


    ORDER_DETAIL_REQUEST : 'ORDER_DETAIL_REQUEST',
    ORDER_DETAIL_SUCCESS : 'ORDER_DETAIL_SUCCESS',
    ORDER_DETAIL_FAIL : 'ORDER_DETAIL_FAIL',
    ORDER_DETAIL_RESET : 'ORDER_DETAIL_RESET',


    ORDER_CHARGE_REQUEST : 'ORDER_CHARGE_REQUEST',
    ORDER_CHARGE_SUCCESS : 'ORDER_CHARGE_SUCCESS',
    ORDER_CHARGE_FAIL : 'ORDER_CHARGE_FAIL',


 }